server:
  port: 6001

#服务的名称
spring:
  application:
    name: zuul-gateway

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5000/eureka/

#自定义路由映射
zuul:
  routes:
    order-service: /abc/**
    user-service: /abcd/**
  #统一入口为上面的配置，其他入口忽略
#  ignored-patterns: /*-service/**
#  #忽略整个服务，对外提供接口
#  ignored-services: order-service
management:
  endpoints:
    web:
      exposure:
        include: "*" #注意这里*要加引号，暴露全部，也可以只暴露相应endpoint
  endpoint:
    routes:
      enabled: true # 默认为true，可以省略
